name: miuicc9e_21.2.2_10

on:
  watch:
    types: [started]87a1_10.0.zip
    
env:
  ROM_URL: https://119-188-133-2.ksyungslb.com/bigota.d.miui.com/21.2.2/miui_LAURUS_21.2.2_bdf7ad0ddd_10.0.zip?ksy_gslb_referer=https%3A%2F%2Fgithub.com%2FmooseIre%2Fupdate_miui_ota%2Fblob%2Fmaster%2FDevelop%2F%25E5%25B0%258F%25E7%25B1%25B3CC%25209e.md
  ROM_NAME: MIUI
  BUILD_AB: true
  BUILD_AONLY: false
  ROM_AONLY: VIOLET_20.11.17_aonly-Q.7z
  ROM_AB: miuicc9e_21.2.2_10.7z

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
       - name: Checkout
         uses: actions/checkout@master
       
       - name: Clean Up
         run: |
           docker rmi `docker images -q`
           sudo rm -rf /usr/share/dotnet /etc/mysql /etc/php /etc/apt/sources.list.d
           sudo -E apt-get -y purge azure-cli ghc* zulu* hhvm llvm* firefox google* dotnet* powershell openjdk* mysql* php*
           sudo -E apt-get update
           sudo -E apt-get -y autoremove --purge
           sudo -E apt-get clean 
           
       - name: Initialization environment
         run: |
            sudo -E apt-get -qq update
            sudo -E apt-get -qq install git openjdk-8-jdk p7zip gzip
       
       - name: Clone ErfanGSI Source Code
         run: git clone --recurse-submodules https://github.com/lkx-0686/ErfanGSIs.git
       
       - name: Setting up ErfanGSI requirements
         run: |
              sudo chmod -R 777 ErfanGSIs
              cd ErfanGSIs
              sudo bash setup.sh
       
       - name: Download Stock Rom & Generate Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -a $ROM_URL $ROM_NAME
       
       - name: 7z Aonly GSI
         if: env.BUILD_AONLY == 'true'
         run: 7za a -t7z -r $ROM_AONLY ErfanGSIs/output/*
       
       - name: Upload Aonly GSI to WeTransfer
         if: env.BUILD_AONLY == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet $ROM_AONLY
           
       - name: Clear output
         if: env.BUILD_AB == 'true'
         run: sudo rm -rf ErfanGSIs/output/*
         
       - name: Download Stock Rom & Generate AB GSI
         if: env.BUILD_AB == 'true'
         run: sudo ./ErfanGSIs/url2GSI.sh -b $ROM_URL $ROM_NAME

       - name: 7z AB GSI
         if: env.BUILD_AB == 'true'
         run: 7za a -t7z -r $ROM_AB ErfanGSIs/output/*

       - name: Upload AB GSI to WeTransfer
         if: env.BUILD_AB == 'true'
         run: |
              curl -sL https://git.io/file-transfer | sh
              ./transfer wet $ROM_AB
         
            
